- package.json
- src/kirby/components/button/button.component.scss
- src/kirby/components/button/button.component.tns.scss
- src/kirby/components/button/button.component.ts
- src/kirby/package.json
- src/kirby/scss/themes/_common-themes.scss
- src/styles.scss
Added colortype attribute to kirby-button - used to indicated which color the button should use from the theme.
> Theming raogf 100 v2

- package-lock.json
- src/kirby/components/card/card.component.scss
Currently, content in a card overflows its rounded corners. 
Example: Adding a background colour to a footer adds sharp corners to the card. 
This should fix the issue, making rounded corners great again. And round.
> Fix overflow outside the rounded corners of cards

- src/app/showcase/chart-showcase/chart-showcase.component.html
- Update _dataLabelsEnabled_ to _showDataLabels_ in showcase to match the new property name
> Update property name in documentation after rename

- src/kirby/components/card/card.component.ts
@jakobe I made the changes locally so i could work with kirby, so thought i could make a PR for it.
> Fixed failing imports in the cards component.

- package-lock.json
- src/kirby/kirby.common.ts
> Fixed the import of list-cell-line.component

- src/app/examples/floating-action-button-example/floating-action-button-example.component.html
- src/app/examples/floating-action-button-example/floating-action-button-example.component.scss
- src/app/examples/floating-action-button-example/floating-action-button-example.component.tns.html
- src/app/examples/floating-action-button-example/floating-action-button-example.component.tns.scss
- src/app/examples/icon-example/icon-example.component.html
- src/app/examples/icon-example/icon-example.component.tns.html
- src/app/showcase/icon-showcase/icon-showcase.component.html
- src/app/showcase/icon-showcase/icon-showcase.component.scss
- src/app/showcase/icon-showcase/icon-showcase.component.spec.ts
- src/app/showcase/icon-showcase/icon-showcase.component.ts
- src/app/showcase/showcase.component.spec.ts
- src/app/showcase/showcase.module.ts
- src/kirby/components/floating-action-button/floating-action-button.component.html
- src/kirby/components/floating-action-button/floating-action-button.component.scss
- src/kirby/components/floating-action-button/floating-action-button.component.spec.ts
- src/kirby/components/floating-action-button/floating-action-button.component.tns.html
- src/kirby/components/floating-action-button/floating-action-button.component.tns.scss
- src/kirby/components/floating-action-button/floating-action-button.component.tns.ts
- src/kirby/components/icon/icon.component.html
- src/kirby/components/icon/icon.component.scss
- src/kirby/components/icon/icon.component.spec.ts
- src/kirby/components/icon/icon.component.tns.html
- src/kirby/components/icon/icon.component.tns.scss
- src/kirby/components/icon/icon.component.ts
Cleanup and small fixes that are missing from last week
> cleanup and last touches on floating action button and icon components

- src/kirby/components/chart/chart.webview.html
Removed alert from Webview.html
> fix(chart):removed alert message

- src/app/component-status/component-status-items.ts
- src/app/page/side-nav/side-nav.component.html
- src/kirby/components/segmented-control/segmented-control.component.scss
The Segmented Control status is now set to ready.
> Setting status to ready for segmented-control

- src/kirby/scss/base/_functions.scss
size('-xl') now gives a negative return value.
> Added option for negative size values

- src/kirby/package.json
Added dependency to nativescript-checkbox (was in root package.json, …but not in source one).
> Fixed missing dependency for nativescript-checkbox

- src/app/examples/floating-action-button-example/floating-action-button-example.component.html
- src/app/examples/floating-action-button-example/floating-action-button-example.component.tns.html
- src/app/showcase/floating-action-button-showcase/floating-action-button-showcase.component.ts
- src/kirby/components/floating-action-button/floating-action-button.component.html
- src/kirby/components/floating-action-button/floating-action-button.component.scss
- src/kirby/components/floating-action-button/floating-action-button.component.spec.ts
- src/kirby/components/floating-action-button/floating-action-button.component.tns.html
- src/kirby/components/floating-action-button/floating-action-button.component.tns.scss
- src/kirby/components/floating-action-button/floating-action-button.component.tns.ts
- src/kirby/components/floating-action-button/floating-action-button.component.ts
> fab now supports a size property

- src/kirby/scss/web/_web-styles.scss
> fix(action-sheet): position of backdrop like kirby-modal

- src/kirby/components/card/card.component.scss
> remove max height from card on web

- src/kirby/components/card/card.component.tns.ts
- src/kirby/scss/scss-helper.tns.ts
> :lipstick: :bug: :robot: Fix card border radius on Android

- src/app/examples/button-example/button-example.component.tns.html
- src/app/examples/button-example/button-example.component.ts
- src/app/examples/icon-example/icon-example.component.html
- src/app/examples/icon-example/icon-example.component.scss
- src/app/examples/icon-example/icon-example.component.ts
- src/app/showcase/button-showcase/button-showcase.component.ts
- src/kirby/helpers/color-helper.ts
Get the colors dynamically for icons from scss-style with color-helper
> feat(icons): get main-colors from scss-styles with color-helper

- src/kirby/directives/nativescript-only/elevation/elevation.directive.tns-only.ts
closes #433 
Thanks to @jonasjensen-brolstark
> fix(elevation): adjust loaded event to wait for iOS aswell

- src/kirby/directives/nativescript-only/elevation/elevation.directive.tns-only.ts
> fix: apply elevation also if elements have already loaded

- src/app/examples/modal-example/modal-example.component.html
- src/app/examples/modal-example/modal-example.component.scss
- src/app/examples/modal-example/modal-example.component.ts
- src/app/showcase/modal-showcase/modal-showcase.component.html
> doc(modal): opening multiple modals from the same view

- src/kirby/components/chip/chip.component.scss
- src/kirby/scss/base/_settings.scss
- src/kirby/scss/base/_typography.scss
> Typography line height

- src/kirby/components/list/list.component.spec.ts
- src/kirby/components/list/list.component.ts
Fixing breaking tests by adding null check in items input for list component.
> test(list): add null check

- src/app/examples/list/base-list.component.ts
- src/kirby/components/list/list-item/list-item.interface.ts
- src/kirby/components/list/list.component.html
- src/kirby/components/list/list.component.ts
- src/kirby/helpers/guid-helper.ts
Fix breaking client because they use reference check for list component (web)
> fix(list): check list item by ref

- src/app/examples/list/list-example.component.html
- src/kirby/components/list/list.component.html
- src/kirby/components/list/list.component.scss
- src/kirby/components/list/list.component.tns.global.scss
- src/kirby/components/list/list.component.tns.html
Closes #508 
Ensure loading is shown outside of list container. Also adjusted sizes and font for show more to make it look consistent between web/native.
Web:
Native:
> style(list): fix no more items styling

- src/kirby/components/slide-button/slide-button.component.html
Fix slide button on mobile by listening for touchend event
> fix(slide-button,web): make slider work on mobile web

- src/app/examples/list/list-example.component.html
- src/kirby/components/badge/badge.component.scss
> :lipstick: :bug: Fix badge in list

- src/kirby/components/card/card.component.scss
> fix(card): removed min height

- src/app/examples/chip-example/chip-example.component.tns.html
- src/app/examples/chip-example/chip-example.component.ts
- src/kirby/components/chip/chip.component.scss
- src/kirby/components/chip/chip.component.tns.global.scss
fixes #520 + minor chip-related fixes.
> style(chip): corrected colours and fixed minor bugs

- src/kirby/components/button/button.component.scss
- src/kirby/components/button/button.component.tns.global.scss
> enhancement(button): added min-width on lg buttons

- src/app/examples/calendar-example/calendar-card-example.component.tns.html
> fix(calendar-example): calendar now shows properly in card example

- src/kirby/components/button/button.component.tns.html
> fix(button): button text on native now shows

- src/kirby/components/modal/action-sheet/action-sheet.component.tns.html
- src/kirby/components/modal/action-sheet/action-sheet.component.tns.ts
- src/kirby/components/modal/modal-wrapper/modal-wrapper.component.tns.ts
- src/kirby/components/modal/nativescript-animations/animations.helper.tns-only.ts
> fix(action-sheet): animations

- src/kirby/components/modal/services/modal.helper.ts
Fixes a bug with the modal positioned at 100% of its height on mobile web.
> fix(modal): animations on mobile web 

- src/kirby/components/empty-state/empty-state.component.scss
- src/kirby/components/empty-state/empty-state.component.tns.scss
> Fix size of outline and placement of icon in EmptyState

- src/kirby/components/list/list.component.html
- src/kirby/components/list/list.component.ts
Reverts the changes from PR #511 as click on nested clickable elements was not possible..
> :rewind: Reverted PR #511

- src/kirby/components/modal/services/modal.helper.ts
Banebrydende og voldsom ændring
> removed top: 40 from transformYFromTo

- src/kirby/scss/_web-imports.scss
- src/kirby/scss/web/_web-styles.scss
DRB has been updated, so I deleted the two temporary scss files that was needed before.
> Removed now unused scss files

- src/kirby/components/loading-overlay/fullscreen-loading-overlay/fullscreen-loading-overlay.component.scss
- src/kirby/package.json
Added missing requirement upon @angular/cdk and fixed bad refer…ence to SCSS-file (not resolving when using library).
> :bug: @angular/cdk and SCSS

- src/kirby/components/avatar/avatar.component.scss
- src/kirby/components/badge/badge.component.scss
- src/kirby/components/segmented-control/segmented-control.component.scss
Closes #577 
Added elevation support on badges. And when used in avatars and segmented control it now has z2 elevation.
I also fixed the position of the badge when used in an avatar, now when i was working on the avatar styling.
> enhancement/elevation support on badge.

- src/kirby/components/button/button.component.scss
> Button with attention level 2 on default/white is now black

- src/kirby/components/grid/grid.component.scss
> :fire: :lipstick: Remove default grid item min height

- src/app/showcase/page-showcase/page-showcase.component.html
- src/app/showcase/page-showcase/page-showcase.component.ts
- src/kirby/components/page/page.component.ts
add enter and leave events for page
> feat(page): add life-cycle hooks

- src/app/examples/examples.routes.ts
- src/app/examples/tabs/tab/tab-example.component.ts
- src/kirby/components/fab-sheet/fab-sheet.component.ts
- src/kirby/components/page/page.component.ts
Make sure sticky header observer works with child routes
closes #718
> fix(page): sticky header on child-routes

- package.json
- src/kirby/testing/kirby-testing.module.ts
:bug: CalendarComponent wasn't provided as a mock in testing module.
> KirbyTestingModule doesn't provide mock of Calendar

- src/app/showcase/page-showcase/page-showcase.component.ts
- src/kirby/components/page/page.component.html
- src/kirby/components/page/page.component.ts
Minor PR for allowing a declarative way of hiding the back button in the Page component.
´
https://github.com/kirbydesign/designsystem/issues/796
> :lipstick: Adding hideBackButton property to Page component

- src/app/examples/page-example/fixed-title-and-actions/page-fixed-title-and-actions-example.component.ts
- src/kirby/components/page/page.component.html
- src/kirby/components/page/page.component.scss
- src/kirby/components/page/page.component.ts
> perf(page): optimize page performance to avoid flickering on iOS

- src/app/examples/alert-example/alert-example.component.html
- src/app/examples/alert-example/alert-example.component.ts
- src/app/examples/empty-state-example/empty-state-example.component.html
- src/app/showcase/alert-showcase/alert-showcase.component.ts
- src/app/showcase/empty-state-showcase/empty-state-showcase.component.ts
- src/kirby/components/empty-state/empty-state.component.scss
Closes #765 
Support for line breaks and spaces in messages in empty state and alerts
> Line break and white space support in empty state

- src/app/examples/divider-example/divider-example.component.html
- src/app/examples/divider-example/divider-example.component.ts
- src/app/showcase/divider-showcase/divider-showcase.component.html
- src/app/showcase/divider-showcase/divider-showcase.component.ts
- src/kirby/components/divider/divider.component.html
- src/kirby/components/divider/divider.component.scss
- src/kirby/components/divider/divider.component.ts
> Add possibility to opt out of margin on divider

- src/app/examples/alert-example/alert-example.component.html
- src/app/examples/alert-example/alert-example.component.ts
- src/app/showcase/alert-showcase/alert-showcase.component.html
- src/app/showcase/alert-showcase/alert-showcase.component.ts
- src/kirby/components/modal/alert/alert.component.html
- src/kirby/components/modal/alert/alert.component.ts
- src/kirby/components/modal/alert/config/alert-config.ts
Allow passing observables to alert title and message.
> feat: support dynamic values in alert

- src/kirby/components/button/button.component.scss
- src/kirby/components/button/button.component.spec.ts
> Disabled button color changed to semi-light-base

- src/kirby/index.ts
> :bug: Exporting IconComponent in index.ts

- src/kirby/components/chart/options/timeseries.ts
- [x ] Bugfix
Markers are all selected when using the chart component.
> Fix for extra markers.

- src/kirby/components/avatar/avatar.component.scss
> Added support for xs avatar

- .github/ISSUE_TEMPLATE/component-request.md
Made a new entry section on component request
> Update issue templates

- src/kirby/testing/kirby-testing.module.ts
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
KirbyToggle not part of the testing module
Issue Number: #924
Kirby Toggle is part of the testing module
> Added Kirby Toggle to testing module

- src/app/changelog/changelog.component.scss
- src/app/examples/button-example/button-example.component.scss
- src/app/examples/icon-example/icon-example.component.scss
- src/app/examples/item-example/item-example.component.scss
- src/app/examples/modal-example/modal-example.component.scss
- src/app/iphone/iphone.component.scss
- src/app/page/side-nav/side-nav.component.scss
- src/app/showcase/colors-showcase/colors-showcase.component.html
- src/app/showcase/colors-showcase/colors-showcase.component.scss
- src/app/showcase/colors-showcase/colors-showcase.component.ts
- src/app/showcase/fonts-showcase/fonts-showcase.component.scss
- src/app/showcase/item-showcase/item-showcase.component.scss
- src/app/showcase/showcase.component.scss
- src/kirby/components/calendar/calendar.component.scss
- src/kirby/components/chip/chip.component.scss
- src/kirby/components/form-field/_form-field-inputs.shared.scss
- src/kirby/components/form-field/form-field-message/form-field-message.component.scss
- src/kirby/components/item/_item.utils.scss
- src/kirby/scss/_global-styles.scss
- src/kirby/scss/base/_functions.scss
- src/kirby/scss/themes/_colors.scss
Closes #776
Issue Number: #776
Kirby now has text colors and a `get-text-color` SCSS function. All components has been updated to use the new function.
> Text colors

- libs/designsystem/src/lib/components/list/list.component.scss
- [ x ] Bugfix
List section headings is bold.
List section headings is NOT bold.
- [ x ] No
> style: reset ion-item-divider font-weight

- apps/cookbook/src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.html
- apps/cookbook/src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.ts
- libs/designsystem/src/lib/scss/_global-styles.scss
:lipstick: Adding hack to temporarily re-enable backdrop on alerts / …action sheets on top of modals.
> Fix for missing backdrops

- libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts
- libs/designsystem/src/lib/components/dropdown/dropdown.component.ts
> 🐛(dropdown) Fix open when inside OnPush host

- libs/designsystem/src/lib/components/modal/services/modal.helper.ts
#988 introduced a bug where the close button of the modal was missing.
Fixes the bug
> :bug: Fix missing close button

- apps/cookbook/src/app/examples/examples.common.ts
- apps/cookbook/src/app/examples/examples.module.ts
- apps/cookbook/src/app/examples/modal-example/modal-example.component.ts
- apps/cookbook/src/app/examples/modal-example/modal-with-footer-example/modal-with-footer-example.component.html
- apps/cookbook/src/app/examples/modal-example/modal-with-footer-example/modal-with-footer-example.component.ts
- apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
- apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
- libs/designsystem/src/lib/components/modal/footer/modal-footer.component.html
- libs/designsystem/src/lib/components/modal/footer/modal-footer.component.scss
- libs/designsystem/src/lib/components/modal/footer/modal-footer.component.ts
- libs/designsystem/src/lib/components/modal/index.ts
- libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.spec.ts
- libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
- libs/designsystem/src/lib/components/modal/services/modal.helper.ts
- libs/designsystem/src/lib/kirby.module.ts
- libs/designsystem/testing-base/src/lib/components/mock.modal-footer.component.ts
- libs/designsystem/testing-base/src/lib/mock-components.ts
> ✨ Modal footer

- libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts
- libs/designsystem/src/lib/components/dropdown/dropdown.component.ts
- package-lock.json
- package.json
- readme.md
This PR closes #991
The dropdown card occasionally drops to the wrong side on Android devices
Issue Number: 991
Now i doesn't :-)
> Fix dropdown on Android

- libs/designsystem/src/lib/components/grid/grid.component.scss
> :lipstick: Use md for grid gap

- libs/designsystem/src/lib/components/stock-chart/stock-chart.component.ts
> Changed boolean to avoid update bug.

- libs/designsystem/src/lib/components/spinner/spinner.component.scss
> Set size of spinner to same size as spinner-overlay

- libs/designsystem/src/lib/components/form-field/input/input.component.spec.ts
> Temporary test fix to make Jenkins happy

- libs/designsystem/src/lib/components/reorder-list/reorder-list.component.scss
Fixing z-index issus on kirby-card in reorder component.
> fix z-index on reorder card

- libs/designsystem/src/lib/components/tabs/tabs.component.html
- libs/designsystem/src/lib/components/tabs/tabs.component.scss
This PR closes #694 
Selected tab button was not highlighted
Selected tab button is highlighted
- [  ] Yes
> Styling of tab bar - Highlight selected tab button

- libs/designsystem/src/lib/components/page/page.component.scss
Toolbar-title on pages with long titles are not truncated
Toolbar-title on pages with long titles are now truncated
> fix(page): ensure .toolbar-title has text-overflow ellipsis

- .travis.yml
Docker image is built for PRs then not used for anything because Travis does not allow pull requests to run deploy scripts
No Docker image built for PR - It will still be built for changes.
> Don't deploy on pull requests

- .gitignore
- libs/designsystem/src/lib/components/grid/grid.component.ts
- libs/designsystem/src/lib/components/list/list.event.ts
> Clean up NativeScript remains

- apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.html
- apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.scss
- apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.ts
- apps/cookbook/src/app/showcase/toggle-button-showcase/toggle-button-showcase.component.html
- apps/cookbook/src/app/showcase/toggle-button-showcase/toggle-button-showcase.component.scss
- apps/cookbook/src/app/showcase/toggle-button-showcase/toggle-button-showcase.component.ts
- libs/designsystem/src/lib/components/index.ts
- libs/designsystem/testing-base/src/lib/components/mock.toggle-button.component.ts
- libs/designsystem/testing-base/src/lib/mock-components.ts
1. Toggle button link
2. Themecolor docs
> toggle-button-cleanup

- libs/designsystem/src/lib/components/list/list.component.ts
- libs/designsystem/src/lib/scss/base/_functions.scss
This PR closes #1166  (reference issue number here)
> fix: is touch device query

- apps/cookbook/src/app/shared/code-viewer/code-viewer.component.html
- apps/cookbook/src/app/shared/code-viewer/code-viewer.component.ts
Code highlight on showcases was only applied on first page load.
Code highlight on showcases is applied on all examples :)
>  📝🐛 Fix code highlight

- libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.scss
In target project a media query regarding padding on modal on >medium gets merged with other media query resulting in wrong order of selectors.
Order is ensured :)
> 🐛 💄 Fix modal padding

- libs/designsystem/src/lib/components/button/button.component.scss
> Fix attention level 3 button losing border on focus

- .github/workflows/build.yml
- .github/workflows/publish.yml
- package.json
> Sparkles rework/publish

- .github/workflows/publish.yml
Currently any change to the repo publishes the Kirby lib to NPM.
Only changes to the libs folder publishes the Kirby lib to NPM.
> Only publish to NPM on lib changes

- libs/designsystem/README.md
> Dummy change for testing npm publish

- .github/workflows/publish.yml
- .scripts/publish.js
- .scripts/test.script
- libs/designsystem/README.md
- scripts/publish.js
> Add Kirby Bot token for version bump

- apps/cookbook/src/app/examples/dropdown-example/examples/right-aligned.ts
> Fix casing in cookbook example

- .github/workflows/build.yml
- .github/workflows/cleanup-branch-deployment.yml
> Add Github Deployment

- .github/workflows/build.yml
- .github/workflows/cleanup-branch-deployment.yml
> Fix deployment clean up

- .github/workflows/publish.yml
Currently a version bump pushes the package.json changes and the new release tag in 2 separate pushes resulting in 2 builds and deploy of the cookbook.
Push package.json changes and release tag in 1 atomic push.
> 👷 Git push version bump in 1 command

- libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
> Clean-up kirby modal footer - modal outlets

- .github/workflows/build.yml
* Currently the deployment of the production cookbook happens multiple times when PRs are merged to master (i.e., 1. when the PRs is merged to master, 2. when a version tag is created, 3. when the version bump is pushed to master).
* Currently branches are deployed right after creation which is redundant as initial deploy is 1:1 with master
* This PRs ensures that the deployment of the production cookbook only happens once when the version bump is pushed to master.
* The deployment of feature branches happens on PRs (create and synchronize events) 
* Also adds GitHub deployments for master/production
> Finetune cookbook deployment

- libs/designsystem/testing-base/src/lib/directives/mock.size.directive.ts
- libs/designsystem/testing-base/src/lib/mock-directives.ts
This PR closes #1335
Issue Number: #1335 
`KirbyTestingBaseModule` now exports `MockSizeDirective`.
> Add mock for Size directive

- libs/designsystem/src/lib/components/list/directives/list-item-color.directive.ts
This PR closes #1336
Make it possible to remove list item color class
> Make it possible to remove list item color class

- libs/designsystem/src/lib/components/page/index.ts
- libs/designsystem/testing-base/src/lib/components/mock.page-footer.component.ts
- libs/designsystem/testing-base/src/lib/mock-components.ts
Adds testing mocks to page footer + exports page footer through page barrel
> chore: page footer testing mocks

- .github/ISSUE_TEMPLATE/housekeeping-request.md
This PR closes #1349
Issue Number: #1349
> Create issue template for Housekeeping

- .github/ISSUE_TEMPLATE/inquiry-request.md
---
----
See [current inquiry template](https://github.com/kirbydesign/designsystem/blob/master/.github/ISSUE_TEMPLATE/inquiry-request.md)
> Spelling and wording in inquiry-request.md

- .github/PULL_REQUEST_TEMPLATE.md
This PR closes #1387 
Issue Number: #1387 
The `.github/PULL_REQUEST_TEMPLATE.md` has had it's wording updated. Take a look at commit 6072f45 😀
> [Housekeeping] Update wording to be issue oriented

- .github/ISSUE_TEMPLATE/bug_report.md
> Fix/missing -- in bug issue template

- .github/workflows/build.yml
no issue - current behaviour is the cookbook doesn't get deployed from master unless the libs package gets published (there is a change to `libs` folder)
Also deploy cookbook on cookbook-only related changes.
> 👷 Deploy cookbook-only related changes

- libs/designsystem/src/lib/components/modal/services/modal-navigation.service.ts
This PR closes #1452 
Issue Number: #1452 
Back navigation works for modal routes with query params.
> 🐛 Fix back navigation for query params

- libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.ts
This PR closes #1476
Issue Number: #1476
https://user-images.githubusercontent.com/150451/115281524-6559ca80-a149-11eb-8350-88bc92e66e12.mov
https://user-images.githubusercontent.com/150451/115281549-6db20580-a149-11eb-9248-41b7da0c0d03.mov
> Fix kirby-radio-group error

- .github/CONTRIBUTING.md
This PR closes #1424 
Issue Number: #1424
A "The good: Issue"-section has been added to the contribution guidelines. Here help is provided to writing good issues.
> "The good: issue" for contribution guidelines

- libs/designsystem/src/lib/components/icon/icon.component.spec.ts
- libs/designsystem/src/lib/components/icon/icon.component.ts
> Added specific warning for build in and custum icons

- libs/designsystem/src/lib/components/badge/badge.component.scss
- libs/designsystem/src/lib/components/badge/badge.component.spec.ts
This PR closes #1492 
Issue Number: #1492 
The badge is now round - which has been achieved by changing the padding by a pixel 😅
I also added tests for checking if it is rendered with the correct height and width when slotting a single character. 
The text in the badge is still rendered a bit differently depending on browser. See images below: 
I will  create a separate issue for having that fixed, such that we can get this bugfix merged and have the badges be round once again ⭕️
I will also go ahead and create an issue for having some testing added to the badge, as none currently exists besides the 3 tests I added for this bugfix.
> [Bugfix] Make Badge Round

- libs/designsystem/ng-package.json
- libs/designsystem/package.json
Add missing dependency "inputmask" inside of our lib
> 🚑 Add inputmask to package.json inside lib

- libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.spec.ts
- libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
- libs/designsystem/src/lib/components/modal/services/modal.helper.ts
> [Bug] Scrollbar disappears briefly when opening Feature Hint Drawer

- package.json
> Hotfixed typo in "transpile:tools" script

- .github/CONTRIBUTING.md
> Documentation: The good self-review

- apps/cookbook/src/app/examples/link-example/examples/new-tab.ts
- apps/cookbook/src/app/examples/link-example/link-example.component.html
- apps/cookbook/src/app/showcase/link-showcase/link-showcase.component.html
- libs/designsystem/src/lib/scss/_global-styles.scss
- libs/designsystem/src/lib/scss/base/_typography.scss
- libs/designsystem/src/lib/scss/base/typography.spec.ts
- libs/designsystem/src/lib/scss/link.spec.ts
This PR closes #770 
Issue Number: #770 
Instead of automatically adding the link icon when target="_blank" is set on the anchor tag, a css-class can be added instead.
> Added css class for external link icon 

- .github/stale.yml
This PR closes #1547 
Housekeeping of issues on github. 
Issue Number: #1547 
probot-stale is already added to the repository, so we need a configuration that fits our usecase.
> Added configuration for stale issue bot

- .github/workflows/build.yml
- libs/designsystem/src/lib/scss/themes/_colors.scss
This PR closes #1519 
Issue Number: #1519
The step responsible for building the distribution files for the cookbook has been moved into a separate job that runs in parallel with the `Lint & Unit test` and `Build Kirby lib`; reducing the runtime for the pipeline.
The original issue suggested using artefacts for transferring dist files between workflows.This however introduced significant overhead in the form of upload & download time.  
Therefore I opted for using caching for transferring the dist files.
We currently do not need to be able to download the dist files after the workflow is done, which is a feature artefacts provides. 
See the below screenshots for time comparisons: …
> Reduced runtime for CI/CD pipeline by building cookbook in parallel with Kirby Lib

- apps/cookbook/src/environments/environment.prod.ts
- apps/cookbook/src/environments/environment.ts
> Chore/update GitHub token

- libs/designsystem/src/lib/scss/themes/_colors.scss
> Make brand colors overridable

- .github/stale.yml
This PR closes no issue. 
Bugs are here to stay!
> Exempted bugs from being marked stale

- libs/designsystem/ng-package.json
- libs/designsystem/package.json
This PR closes #1684 
Added the annotations plugin so our published package has it as a dependency.
> Add annotation plugin as dependency for published package

- .github/workflows/build.yml
This PR closes #1694 
The cookbook is successfully deployed.
> Fix failing CI/CD job

- apps/cookbook/src/app/page/side-nav/side-nav.component.html
This PR closes #1692 
All navigation items are displayed regardless of viewport width.
> Fix links missing from side navigation

- libs/designsystem/src/lib/components/icon/kirby-icon-settings.ts
- libs/designsystem/src/lib/icons/svg/remove.svg
This PR closes #1697
A new 'remove' icon has been added to Kirby. 
> Add a 'remove' icon to default icons

- libs/designsystem/src/lib/components/item/item.component.scss
This PR closes #1689 
No additional padding
> Remove additional padding from kirby-item

- apps/cookbook/src/app/showcase/default-list-showcase/default-list-showcase.html
- libs/designsystem/src/lib/scss/_global-styles.scss
- libs/designsystem/src/lib/scss/base/_lists.scss
- libs/designsystem/src/lib/scss/base/_typography.scss
> Enhancement/1391 default list styling  refactor

- apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
- libs/designsystem/src/lib/components/router-outlet/index.ts
This PR closes #1760 
The [NavController]() class from `@ionic/angular` has been exposed via Kirby. This should allow for consumers of Kirby to navigate the history stack when using pages with `kirby-router-outlet`. 
I've also made some changes to the `kirby-router-outlet` documentation - but kept it simple. See additional context.
I think we could use some more documentation for `kirby-router-outlet` and the stacked navigation. I will go ahead and create an issue to have this more properly documented. I did not do it as part of this PR as I would like to invest some more time to investigate its usage a bit more, and if it is being used in other contexts than this one. 
I honestly don't know a whole lot about the `kirby-router-outlet`. 
The following tasks should be carried out in …
> Re-export NavController class from @ionic/angular

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/component-request.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR closes no issue, I went rogue!
I changed some of the relative links to absolute links so they are not dead. 
> Fix issue template links to contribution guidelines

- apps/cookbook/src/app/app.module.ts
This PR closes #1777
The cookbook app should now match the route correctly when accessed via a direct link.
To verify it works, try copying the deployment link from this PR and pasting it in a new blank tab in your favourite browser. 
~~- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".~~
~~- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).~~
~~- [ ] Request that the changes are [UX …
> Use HashLocationStrategy for routing

- apps/cookbook/src/app/app.module.ts
This reverts commit 44de07e2035bbee0549524a2e1948b02d4c5ada4.
> Revert "Use HashLocationStrategy for routing (#1778)"

- apps/cookbook/src/app/app.module.ts
- apps/cookbook/src/app/iphone/iphone.component.ts
This PR closes #1777
#1778 had already been merged to fix this but it had to be reverted in #1779 as it caused the iPhone previews to not work. 
> Use HashLocationStrategy for routing & make phone-previews HashLocationStrategy compatible

- apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
This PR closes #1801 
It improves the documentation for the modal navigation.
> Added additional help for the modal navigation.

- libs/designsystem/src/lib/components/modal/services/action-sheet.helper.spec.ts
- libs/designsystem/src/lib/components/modal/services/action-sheet.helper.ts
- libs/designsystem/src/lib/scss/_global-styles.scss
> Enable close on backdrop click for action sheets

- libs/designsystem/src/lib/directives/element-as-button/element-as-button.directive.spec.ts
This PR closes ~~# (insert issue number here)~~ none
The defect was introduced in https://github.com/kirbydesign/designsystem/pull/1838
> Fix a faulty test

- apps/cookbook/src/app/showcase/fonts-showcase/fonts-showcase.component.html
> Fixed typo for font size small & xx-small text

- .github/workflows/publish.yml
> 🐛 [ EXPERIMENT ] Should run when PR is merged

- .github/workflows/publish.yml
- libs/core/src/scss/_global-styles.scss
- libs/core/src/scss/_trigger-publish-workflow.scss
> 🐛 [EXPERIMENT] Bugfix/1947 fix publish workflow

- .github/workflows/publish.yml
This PR closes #1947 
We need to trigger the publish workflow when a pull request targeting `master` is merged. There is no `merge` webhook event, so this change listens for `push`. We expect push to master only when a pull request is merged.
> 💚 Trigger publish workflow on push to master

- libs/core/src/scss/_global-styles.scss
> ⚗️ Experiment: Verify that publish workflow runs on merge PR

- .github/workflows/publish.yml
- libs/core/src/scss/_global-styles.scss
This PR closes NO ISSUE
This PR will revert changes made in a previous PR (#1955). We still need the issue to fix the original bug (#1947)
No new behavior. Just revert changes.
> ⏪ Revert changes to publish workflow

- .github/workflows/publish.yml
Does a push to base branch trigger another run of the publish workflow?
> ⚗️ Experiment 1

- .github/workflows/publish.yml
> ⚗️ Add a simple change #2

- .github/workflows/publish.yml
> ⚗️ Add simple change

- .github/workflows/publish.yml
> ⚗️ Add simple change (take 4)

- .github/workflows/publish.yml
> ⚗️ Add simple change (take 5)

- .github/workflows/publish.yml
> ⚗️ Add simple change (take 6)

- libs/core/src/scss/_global-styles.scss
- libs/core/src/scss/_trigger-publish.scss
> ⚗️ Add changes to trigger publish workflow (take 1)

- .github/actions/push-version-bump-and-tag/action.yml
- .github/workflows/publish.yml
> Fix publish workflow

- libs/core/src/helpers/color-helper.scss
- libs/core/src/helpers/design-token-helper.scss
- libs/core/src/scss/themes/_colors.scss
This PR closes #1992 
`generate-colors()` will assign values of type `color` instead of `string`. The built-in color module functions, e.g., `color.scale()`, expect arguments of type `color`, which is any valid CSS color.
See https://sass-lang.com/documentation/values/colors and https://sass-lang.com/documentation/modules/color
Please compare https://cookbook.kirby.design/branch/kby-1992-fix-generate-colors/#/home/showcase/colors to https://cookbook.kirby.design/#/home/showcase/colors. They should be identical.
When the pull request has been approved it will be …
> Fix `generate-colors()` Sass function

- angular.json
- libs/core/src/scss/base/_variables.scss
- libs/core/src/scss/interaction-state/_hover.scss
- libs/designsystem/src/lib/components/button/button.component.scss
- libs/designsystem/src/lib/components/calendar/calendar.component.html
- libs/designsystem/src/lib/components/calendar/calendar.component.scss
This PR closes #2007 
Changes based on UX review have been made:
- Solution for buttons with transparent background added
- Loudness adjusted - dark backgrounds louder, light backgrounds quieter (e.g. attention level 2)
- Buttons in `.kirby-color-brightness-dark` context modified
- Calendar: Buttons in month navigator
- Notification colors (success etc.) in e.g. Alert
- Modal wrapper
- Toggle button
Still Awaiting UX decision:
- Action Sheet
- Dropdown
When the pull request has been approved it will be automatically merged to master via …
> Adjust hover in components that use kirby-button

- apps/cookbook/src/app/showcase/chart-showcase/chart-showcase.component.html
This PR closes no issues. 
Some of the links for the chart showcase page were dead. So i resurrected them 👼
> Documentation: Fix dead links on chart showcase page

- libs/core/src/scss/interaction-state/_index.scss
- libs/core/src/scss/interaction-state/_utilities.scss
- libs/designsystem/src/lib/components/checkbox/checkbox.component.scss
> Interaction state hover for checkbox

- libs/core/src/scss/interaction-state/_layer.scss
- libs/designsystem/src/lib/components/radio/radio.component.scss
> Interaction state hover for radio button

- libs/designsystem/src/lib/components/toggle/toggle.component.scss
> Interaction state for toggle

- libs/designsystem/src/lib/components/range/range.component.scss
> Interaction state hover for range

- apps/cookbook/src/app/examples/card-example/examples/card-background-image-example.component.ts
- apps/cookbook/src/app/examples/card-example/examples/card-css-background-image-example/card-css-background-image-example.component.ts
- libs/designsystem/src/lib/components/card/card.component.html
- libs/designsystem/src/lib/components/card/card.component.scss
- libs/designsystem/src/lib/directives/element-as-button/element-as-button.directive.spec.ts
> Hover solution for non solid backgrounds in card

- libs/core/src/scss/interaction-state/README.md
> Scaffold documentation for interaction state

- libs/designsystem/src/lib/components/checkbox/checkbox.component.scss
- libs/designsystem/src/lib/components/form-field/input/input.component.scss
- libs/designsystem/src/lib/components/radio/radio.component.scss
- libs/designsystem/src/lib/components/range/range.component.scss
- libs/designsystem/src/lib/components/slide-button/slide-button.component.scss
- libs/designsystem/src/lib/components/toggle/toggle.component.scss
Forgot to fix these when doing #2211 
~~This PR closes # (insert issue number here)~~
> Refactor loudness scale get-state-color()

- MIGRATION.md
- readme.md
I have compiled information on all the breaking changes in the upcoming v6 release in a MIGRATION.md file at the root of the repo: https://github.com/kirbydesign/designsystem/blob/d1b52bbcb43a460cec24023d714ea2070a0141d1/MIGRATION.md
> Migration notes v6

- libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts
- libs/designsystem/src/lib/components/dropdown/dropdown.component.scss
- libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts
- libs/designsystem/src/lib/components/item-sliding/item-sliding.component.spec.ts
- libs/designsystem/src/lib/components/modal/services/action-sheet.helper.spec.ts
This PR closes #1836 
Fix of reported flaky. tests in kirby.
> Fix Reported Flaky Tests

- libs/core/src/scss/interaction-state/_hover.scss
- libs/core/src/scss/interaction-state/_interaction-state.utilities.scss
- libs/core/src/scss/interaction-state/_layer.scss
- libs/core/src/scss/interaction-state/ionic/_hover.scss
This PR closes #2200 
Just a teeny tiny renaming.
> Rename $default-loudness to $default-loudness-hover

- libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.html
> Fix supplementary action button in Modal with nested Drawer

- libs/core/src/scss/interaction-state/_interaction-state.utilities.scss
> Adjust transition duration

- libs/core/src/scss/base/_link.scss
> Add transition effect for links

- libs/core/src/scss/base/_link.scss
- libs/core/src/scss/interaction-state/_focus.scss
- libs/core/src/scss/interaction-state/_interaction-state.utilities.scss
- libs/core/src/scss/interaction-state/_layer.scss
- libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.scss
- libs/designsystem/src/lib/components/form-field/input/input.component.scss
- libs/designsystem/src/lib/components/form-field/textarea/textarea.component.scss
- libs/designsystem/src/lib/components/item/item.component.scss
- libs/designsystem/src/lib/components/page/page.component.scss
- libs/designsystem/src/lib/components/radio/radio.component.scss
- libs/designsystem/src/lib/components/range/range.component.scss
- libs/designsystem/src/lib/components/segmented-control/segmented-control.component.scss
- libs/designsystem/src/lib/components/slide-button/slide-button.component.scss
> Extend transition for interaction states

- libs/core/src/scss/base/_functions.scss
- libs/core/src/scss/base/_variables.scss
- libs/core/src/scss/interaction-state/_interaction-state.utilities.scss
- libs/core/src/scss/interaction-state/_layer.scss
> Move loudness scale helpers

- libs/core/src/scss/base/_functions.scss
This PR closes no issue.
This module was missing in https://github.com/kirbydesign/designsystem/issues/2162.
> 💄 Add missing import statement

- package-lock.json
- package.json
This is just a package bump for the 5.4 release (#2287)
> Update package version to 5.4.0

- apps/cookbook/src/app/examples/grid-layout-example/grid-layout-extended-example/grid-layout-extended-example.component.scss
- apps/cookbook/src/app/examples/grid-layout-example/grid-layout-multiple-containers-example/grid-layout-multiple-containers-example.component.scss
- apps/cookbook/src/app/examples/grid-layout-example/grid-layout-single-container-example/grid-layout-single-container-example.component.scss
- libs/core/src/scss/base/_functions.scss
This PR closes #2225 
No new behavior.
https://sass-lang.com/documentation/breaking-changes/slash-div
> Migrate Sass division

- libs/core/src/scss/interaction-state/_layer.scss
> Migrate sass division (part 2)

- angular.json
This PR closes NO ISSUE
Cookbook build won't fail due to non-critical, arbitrary file size budget (button component stylesheet).
> Remove budget from cookbook

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/component-request.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build.yml
- .github/workflows/publish.yml
- apps/cookbook/src/app/showcase/badge-showcase/badge-showcase.component.html
- apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.html
- apps/cookbook/src/app/showcase/showcase.component.ts
- readme.md
This PR closes #2291
<table>
<tr>
<th>Old name</th>
<th>New name</th>
<th>Description</th>
</tr>
<tr>
<td>main</td>
<td>develop</td>
<td>The main development branch</td>
</tr>
<tr>
<td>stable</td>
<td>main</td>
<td>Reflect latest published version and must always be stable</td>
</tr>
</table>
Right before merging this, we should rename the stable branch to main on github, for our CI environment to work. 
When the pull request has been approved it will be automatically merged to `stable` via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull …
> Rename branches to follow Git Flow conventions

- libs/core/package-lock.json
- libs/core/package.json
- libs/designsystem/package.json
- package-lock.json
- package.json
This PR closes NO ISSUE
No new behavior.
> Sync main to develop

- libs/designsystem/src/lib/components/reorder-list/reorder-list.component.scss
Fixes https://github.com/kirbydesign/designsystem/issues/2344
> Fix rounded corners on Reorder List

- libs/designsystem/src/lib/components/segmented-control/segmented-control.component.scss
Should use same loudness levels as Chip
Closes https://github.com/kirbydesign/designsystem/issues/2345
**Before**
Captured on https://cookbook.kirby.design/branch/kby-v7-0-0/#/home/showcase/segmented-control
https://user-images.githubusercontent.com/150451/175017508-14bef0ae-7b24-4726-b0c0-676a66437b6a.mov
**After**
Captured running on localhost
https://user-images.githubusercontent.com/150451/175017557-461cddf2-55c9-4b52-a0fd-5b0db7e78520.mov
**NB: About focus**
I have no idea why there's a visible focus ring in _After_ but not in _Before_. No changes have been made to focus state in this PR.
The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/mai …
> Increase loudness level on selected segment

- CHANGELOG.md
This is just a PR to update the changelog file with information about version 6.1.1.
See rendered version here: https://github.com/kirbydesign/designsystem/blob/update-changelog-version-6.1/CHANGELOG.md
> ✨ Update changelog

- apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.html
This PR closes #2383 
We correctly describe what is needed for the animation of accordion to work in projects. 
> Add note for using Accordion

- CHANGELOG.md
- apps/cookbook/src/app/examples/accordion-example/accordion-example.module.ts
- apps/cookbook/src/app/examples/accordion-example/examples/default.ts
- apps/cookbook/src/app/examples/calendar-example/calendar-card-example.component.html
- apps/cookbook/src/app/examples/calendar-example/calendar-card-example.component.ts
- apps/cookbook/src/app/examples/page-example/fixed-title-and-actions/page-fixed-title-and-actions-example.component.ts
- apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.html
- apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.ts
- apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.html
- apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.ts
- apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.ts
- libs/core/package.json
- libs/designsystem/package.json
- libs/designsystem/src/lib/components/accordion/accordion-item.component.html
- libs/designsystem/src/lib/components/accordion/accordion-item.component.scss
- libs/designsystem/src/lib/components/accordion/accordion-item.component.spec.ts
- libs/designsystem/src/lib/components/accordion/accordion-item.component.ts
- libs/designsystem/src/lib/components/calendar/calendar.component.spec.ts
- libs/designsystem/src/lib/components/calendar/calendar.component.ts
- libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.ts
- libs/designsystem/src/lib/components/page/page.component.spec.ts
- libs/designsystem/src/lib/components/page/page.component.ts
- libs/designsystem/src/lib/components/segmented-control/segmented-control.component.spec.ts
- libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts
- package-lock.json
- package.json
**accordion** - add note for using Accordion in microfrontends (#2436)
**fab-sheet** - fix backdrop showing up when fab is closed (#2459)
**page** - fix emission of enter and leave events (#2387)
**segmented-control** - add option for setting selectedIndex in segmentSelect call-back (#2407)
**accordion** - add option to disable accordion items (#2451)
**calendar** - add option to specify which dates should be enabled (#2454)
> Release version 6.4

- CHANGELOG.md
> Update changelog with v7 entry

- readme.md
This PR closes no issue.
Link in README to contribution page works as intended.
> Fix link to contribution guidelines

- libs/core/package.json
- libs/designsystem/package.json
- package-lock.json
- package.json
- **icons** - new icons: help-decoration, information-decoration, notification, transfer-ownership ([#2504](https://github.com/kirbydesign/designsystem/pull/2504))
- **list** - sub sections ([#2478](https://github.com/kirbydesign/designsystem/pull/2478))
- **accordion** - always close accordion when disabled ([#2499](https://github.com/kirbydesign/designsystem/pull/2499))
- **item** - toggles inside kirby item placed too high ([#2518](https://github.com/kirbydesign/designsystem/pull/2518))
- **page** - fix memory leak in kirby-page ([#2519](https://github.com/kirbydesign/designsystem/pull/2519))
- **toolbar** - use kirby black on ion-toolbar and ion-content ([#2520](https://github.com/kirbydesign/designsystem/pull/2520))
> Release v7.1.0

- libs/core/package-lock.json
- libs/core/package.json
- libs/designsystem/package.json
- package-lock.json
- package.json
Fix missing scss folder in core package
> Release v7.1.1

- apps/cookbook/src/app/examples/examples.routes.ts
- libs/designsystem/src/lib/components/data-table/table/table.component.scss
- libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
- libs/designsystem/src/lib/components/tabs/tab-button/tab-button.component.scss
- package-lock.json
This PR closes no issue, it is a hotfix after #2538
> Fix cookbook examples after Angular 14 upgrade
