src/kirby/components/card/card.component.tns.scss

It should not display as "height 100%".

Changed TNS styling for Card component

---

src/kirby/components/list/list.component.tns.html

If there is a kirby list without sections headers the app would crash on iOS. This was do to, that the section header template was still rendered but just empty. This would lead to an error, in the radlistview code on the OnDestroy lifecycle hook.
I fix this with a simple ngIf.
Fixes #90

Bugfix: App crashes when navigating away from kirby list without section headers.

---

src/kirby/components/card/card.component.tns.ts

Kirby card was not able to hook into standard event and layout functionality for {N}. This has now been fixed (so that you can bind to tab-events, use rows- and cols-attributes when combined with GridLayout, etc.)

Kirby card as registered nativescript element

---

package-lock.json
package.json

I have locked the version of highchart as version 7.1.0 has breaking changes.
Until now the version of highchart was set to `^7.0.3` in `package.json`. Highchart was released in version `7.1.0` with breaking changes. That mean after a `npm i` kirby can no longer build and even worse, users of Kirby can not build there apps.
So i have locked the version to `7.0.3` for now. I could have put to autoupdate patches. But i don't think there will be a version `7.0.4` as version `7.1.0` has been released.

locked the version of highchart.

---

src/kirby/components/button/button.component.tns.html

in {N} it is possible to have a `FormattedString` inside a `Button` tag like:
```html
<Button>
<FormattedString>
<Span text="foo" fontSize="60"></Span>
<Span text="bar" fontSize="10"></Span>
</FormattedString>
</Button>
```
But right now the tns view for `kirby-button` is not rendering any containing elements for a `Button`.
I have fixed this by adding a `ng-content` tag.

Added ng-content to nativescript button view.

---

tsconfig.json

(as {N} re-adds `"~/*"` on clean npm install)

:bug: Fix tsconfig app path

---

src/kirby/components/segmented-control/segmented-control.component.tns.scss

Added a color for the un-selected segment. 
Reason: 
In DRB we will be setting every elements font color to get-color('contrast-dark') in order to fix the android grey fonts. So without a set font on the segment, it will get a wrong color.

Added color for unselected segment

---

src/kirby/directives/size/size.directive.spec.ts
src/kirby/directives/size/size.directive.ts

add exported enum of sizes, so we don't need to hardcode the sizes allover.

feat(size): add sizes enum which is exported from size directive

---

nsconfig.json
package-lock.json
package.json
webpack.config.js

>Requires {N} CLI ^5.4
- because the new workflow uses --bundle and --hmr by default I removed the redundant params in npm scripts

update to {N} 5.4

---

src/kirby/components/modal/services/modal.controller.ts

There is a bug where on a timeout then modals isn't closed correctly - so the welcome page can still be visible even though you aren't logged in. 
So we have to somehow trigger a close everything when timing out. So that is why we've added a hideAll function to the modal.

Enhancement/Modal - hideAll function

---

src/app/showcase/icon-showcase/icon-showcase.component.html

The documentation refers to `CustomIconSettings` and `CUSTOM_FONT_SETTINGS` which are now renamed. This should be reflected in the docs.

Fix reference to IconSettings in docs

---

src/kirby/components/list/list.component.tns.html

Fix for #418 .
I wrapped the template outlet with a `StackLayout` as suggested in [here](https://github.com/NativeScript/nativescript-angular/issues/93) and it removed the issue in the cookbook.

Fixed list header for native.

---

src/app/examples/chip-example/chip-example.component.html
src/app/examples/chip-example/chip-example.component.scss
src/app/examples/chip-example/chip-example.component.tns.html
src/app/examples/chip-example/chip-example.component.tns.scss
src/app/examples/chip-example/chip-example.component.ts
src/app/showcase/chip-showcase/chip-showcase.component.html
src/app/showcase/chip-showcase/chip-showcase.component.ts
src/kirby/components/chip/chip.component.scss
src/kirby/components/chip/chip.component.tns.global.scss
src/kirby/components/chip/chip.component.tns.scss
src/kirby/scss/native/_native-common.scss

Closes #380
- Support theming for chip button. Native and web.
- Added global style for chip native to overcome the view encapsulation
- Updated cookbook with theming examples for chip
Web:
Native:

feat(chip): support theming for chip native and web

---

src/app/examples/nativescript-only/list-section-example/list-section-example.component.tns.html

Renamed an occurrence of verifiy to verify resulting in an error when the list with sections example is opened

Fix / Icon name typo

---

src/app/examples/card-example/card-example.component.html
src/app/examples/card-example/card-example.component.scss
src/app/examples/card-example/card-example.component.tns.html
src/app/examples/card-example/card-example.component.tns.scss
src/app/examples/card-example/card-example.component.ts
src/app/examples/card/card-elevations-example/card-elevations-example.component.html
src/app/examples/card/card-themecolor-example/card-themecolor-example.component.html
src/app/examples/card/card-themecolor-example/card-themecolor-example.component.scss
src/app/showcase/card-showcase/card-showcase.component.html
src/app/showcase/card-showcase/card-showcase.component.scss
src/kirby/components/card/card-header/card-header.component.tns.scss
src/kirby/components/card/card.component.html
src/kirby/components/card/card.component.scss
src/kirby/components/card/card.component.tns.html
src/kirby/components/card/card.component.tns.scss
src/kirby/components/card/card.component.tns.ts
src/kirby/components/card/card.component.ts

Closes #531
Only apply padding for card content and don't make padding default
Native:
Web:

feat(card): only apply padding for content and no breaking

---

src/app/examples/examples.routes.ts

I added the missing routes for the list-swipe and list-load-on-demand examples. So now the pop-outs works.

:bug: Pop-out routes added for lists.

---

src/kirby/components/modal/services/action-sheet.helper.ts
src/kirby/components/modal/services/modal.controller.ts
src/kirby/components/modal/services/modal.helper.ts

Removed `ViewContainerRef` (well, made it optional for now) from `ModalController`, to avoid leaking memory, when displaying modals from Effects.
When dependant code has removed the usage of the `ViewContainerRef`, the API of kirby can delete the argument completely (doing it this way to minimize the impact of this optimization).

:bug: Removing unused ViewContainerRef from ModalController.

---

src/app/examples/action-sheet-example/action-sheet-example.component.ts
src/app/examples/alert-example/alert-example.component.ts
src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.ts
src/app/examples/modal-example/modal-example.component.ts
src/kirby/components/modal/services/action-sheet.helper.ts
src/kirby/components/modal/services/modal.controller.interface.ts
src/kirby/components/modal/services/modal.controller.ts
src/kirby/components/shared/component-loader.directive.ts

Removes `ViewContainerRef` from modals, action sheets and alerts completely (was previously an optional 2nd parameter).

[Clean up] Remove ViewContainerRef

---

src/kirby/testing/kirby-testing.module.ts

:bug: Jasmine mocks in KirbyTestingModule had the potential to leak state (since mocks were created once, and being able to share state between test-case executions).
This fixes the issue by providing a factory for the module... hence, providing a new instance of the mock(s), for every TestBed that imports the `KirbyTestingModule`.

KirbyTestingModule can leak state

---

src/kirby/components/divider/divider.component.scss

:bug: Divider didn't have a default color (unless placed in element with parent having class set to `.default`).

Divider without color

---

src/app/examples/divider-example/divider-example.component.html
src/kirby/components/divider/divider.component.scss

When the divider was added to a modal or something else with `background-color` as background color, it would be invisible (also have `background-color` as color).
Now it will have `background-color` as color when in Card, unless the card has either `white` or `light` theme color. If not in card it will have `medium` as color.

Divider color on background

---

src/kirby/components/button/button.component.scss

Fix wrong styling of buttons in context of page. Buttons should now be styled correctly inside of an page toolbar and page header.
**Can be tested by running ng serve --prod**

fix(button): styling of button in context of page

---

src/kirby/components/button/button.component.scss

Fixes an issue where buttons inside page titles are styled like page actions
*Wrong:*
*Correct:*

:lipstick: :bug: Only style buttons inside kirby-page-actions

---

src/app/examples/segmented-control-example/segmented-control-example.component.ts
src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.html
src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.ts
src/kirby/components/segmented-control/segment-item.ts
src/kirby/components/segmented-control/segmented-control.component.html

SegmentedControl is now more accessible by people with low vision. 
When a screen reader reads a segmented control it does the following:
- For default mode, the badge is read a text **before** the button
- For chip mode, every chip is read as text
When a screen reader reads a segmented control it does the following:
- For default mode, the badge is read a text **after** the button, and the `description` of the badge is read instead of the text in the badge
- For chip mode, every chip is read as a button

Segmented control accessibility

---

libs/designsystem/src/lib/components/reorder-list/reorder-list.component.scss

No rounded corners on reorder list Kirby items
Round corners for items in reorder list.
- [ x ] No

fix: fix reorder list rounded corners for ios

---

libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.html
libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.spec.ts
libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
libs/designsystem/testing-base/src/lib/components/mock.calendar.component.ts

This PR fixes a transient modal bug that was introduced with #1003
* Sometimes the blurring of an active element in the touchstart event handler prevents the tap/click handler to fire on toolbar buttons. This in turn prevents the modal from being closed on first click.

:bug: Fix modal close button

---

libs/designsystem/src/lib/components/list/list.component.scss

This PR fixes a transient iOS bug that was introduced in #863 that sometimes make the rounded corners on list sections disappear (making them squared)

💄🐛🍏Fix for list rounded corners on iOS

---

apps/cookbook/src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.html
apps/cookbook/src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.ts
apps/cookbook/src/app/examples/modal-example/modal-example.component.ts
apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
libs/designsystem/src/lib/components/modal/modal-wrapper/compact/modal-compact-wrapper.component.ts
libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.spec.ts
libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
libs/designsystem/src/lib/components/modal/services/modal.interfaces.ts

With the current behaviour you can't disable scrolling of a modal
You can now toggle scrolling of a modal by setting scrollDisabled=true|false

feat(modal): add scrollDisabled property, to toggle scrollY

---

apps/cookbook/src/app/examples/item-example/examples/card.ts
apps/cookbook/src/app/examples/item-example/item-example.component.html
apps/cookbook/src/app/examples/item-example/item-example.module.ts
apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.html
libs/designsystem/src/lib/components/card/card.component.scss

closes #1052
Issue Number: 1052
The kirby-card is no longer sqaure if it includes a kirby-item.

kirby item is now correctly rendered behind the kirby card

---

libs/designsystem/src/lib/components/form-field/_form-field-inputs.shared.scss
libs/designsystem/src/lib/components/form-field/input/input.component.integration.spec.ts
libs/designsystem/src/lib/components/form-field/input/input.component.spec.ts

Added explicit default padding to input element of 0px and un-commented a test that previously failed on Jenkins.

Added explicit default padding to input field

---

libs/designsystem/src/lib/components/icon/_icon.component.shared.scss
libs/designsystem/src/lib/components/icon/icon.component.scss

This PR closes # N/A
Add xs size support for icons
Currently icons with size 'xs' are shown in Cookbook - however they are displayed with the same size as icons having size 's'. 
When specifying size xs on an icon, it is now correctly rendered as font-size('s') ie. 16px

Added xs sized icon support

---

libs/designsystem/src/lib/components/page/page.component.scss

Currently the page toolbar is capped at 768px max-width.
See: https://github.com/kirbydesign/designsystem/issues/965
Issue Number: 965
max-width is only enforced if toolbar is displayed on a large non-touch device. This way the toolbar will be full width as is expected on native devices.

:art: Removing max-width for ion-header and ion-toolbar on tablet

---

libs/designsystem/src/lib/components/list/list.component.scss

In some scenarios at iOS the round corners are overflowed and therefore disappear 
Adding following at ion-item-sliding ensures that doesn't happen:
`-webkit-mask-image: -webkit-radial-gradient(
white,
black
);`

fix(list): ensure round corners at iOS, before round corners could disappear when rotating an iPad in special scenarios

---

apps/cookbook/src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.html
apps/cookbook/src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.scss
apps/cookbook/src/app/examples/modal-example/first-embedded-modal-example/first-embedded-modal-example.component.ts
apps/cookbook/src/app/examples/modal-example/modal-example.component.ts
apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
libs/designsystem/src/lib/components/modal/footer/modal-footer.component.scss
libs/designsystem/src/lib/components/modal/footer/modal-footer.component.spec.ts
libs/designsystem/src/lib/components/modal/footer/modal-footer.component.ts
libs/designsystem/testing-base/src/lib/components/mock.modal-footer.component.ts

The kirby modal footer always slides in with the soft keyboard on devices.
A flag to control if the modal footer should stay fixed to the bottom or if it should slide in with ("snap to") the keyboard.
The flag has been named `snapToKeyboard` and is defined as an attribute on the `<kirby-modal-footer>` element. If omitted, it will default to false.
This requires existing usages (there is just one) to define the flag to true to stay the same. We should make a separate bump of Kirby in DRB, fixing this as part of the bump.
The main design decisions were made in collaboration with @jakobe prior to the summer holidays.

Modal footer snap to keyboard optional

---

libs/designsystem/src/lib/components/calendar/calendar.component.spec.ts
libs/designsystem/src/lib/components/calendar/calendar.component.ts

Specifically, when using locale in which weeks don't start on a Monday, such as "en-US" or "en", but presumably also a host of other locales around the globe.
This PR closes #1123
Issue Number: 1123
Labels for weekdays are rendered Monday .. Sunday regardless of locale. This matched the dates rendered below.

Bugfix: weekday labels were off when using some locales

---

libs/designsystem/src/lib/components/form-field/form-field.component.spec.ts
libs/designsystem/src/lib/components/form-field/form-field.component.ts

Workaround until ionic fixes input click problem:
https://github.com/ionic-team/ionic-framework/issues/22740

fix-readonly-input-click

---

libs/designsystem/src/lib/components/item/item.component.scss

With Capacitor it is not triggering click first time if:
1. Ion content with some padding (50px here) and scrollEvents true
2. --background-activated-opacity: 1 and "button" on item
3. Scroll to very bottom of list and click on an item
4. See list i "moving" and click is ignored, second click will work
Click is ignored as in video
With Capacitor it is not triggering click first time if:
1. Ion content with some padding (50px here) and scrollEvents true
2. --background-activated-opacity: 1 and "button" on item
3. Scroll to very bottom of list and click on an item
4. See list i "moving" and click is ignored, second click will work …

fix: ignored click item in when scrollend (ios)

---

apps/cookbook/src/app/examples/empty-state-example/empty-state-example.component.html
libs/designsystem/src/lib/components/empty-state/empty-state.component.integration.spec.ts
libs/designsystem/src/lib/components/empty-state/empty-state.component.spec.ts
libs/designsystem/src/lib/components/empty-state/empty-state.component.ts

This PR closes #1222. 
Issue Number: #1222 
When a `emptyStateComponent` has `button`-children all of them will have their attention level set to 3; except the first one with attention level 1. This also applies if buttons are dynamically added or removed from the `emptyStateComponent`. 
This is a draft as I still have to add tests for adding and removing button children from the emptyStateComponent. I however need a bit of help with this; see comments.

Empty state button rules

---

.github/ISSUE_TEMPLATE/bug_report.md

This PR closes #1362
Issue Number: #1362 
I have replaced the "NOT Tech refined" label with "NOT Verified" in `bug_report.md` template and updated tasks accordingly.

[Enhancement] Replace 'NOT Tech refined' label with 'NOT Verified' for bug template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/component-request.md
.github/ISSUE_TEMPLATE/enhancement-request.md
.github/ISSUE_TEMPLATE/housekeeping-request.md

This PR closes #1446 
Added the existing 'New' label on all the issue tempaltes (Inquiry already had 'New' label).
Github Templates addition!
Issue Number: .
The 'new' label gets added by default now on all issues.

Housekeeping/'New' label on GitHub issue templates

---

libs/designsystem/src/lib/components/button/button.component.integration.spec.ts
libs/designsystem/src/lib/components/button/button.component.scss
libs/designsystem/src/lib/components/button/button.component.spec.ts
libs/designsystem/src/lib/components/list/list.component.scss
libs/designsystem/src/lib/components/slide-button/slide-button.component.scss
libs/designsystem/src/lib/scss/themes/_colors.scss

This PR closes #1395
Please check if your PR fulfils the following requirements:
Attention level 3 and 4 buttons have transparent background color (not part of change). They are expected to be displayed on a light background color, so this change makes their (text) color `black` instead of `primary-contrast`. With Skjern Bank brand colors `primary-contrast` is `white`. For all other brands `primary-contrast` is `black`.
Issue Number: #1395
Text color for attention level 3 and 4 buttons will be `black` regardless of brand colors.

Fix wrong colour (Skjern Bank brand)

---

libs/designsystem/src/lib/components/progress-circle/progress-circle-ring.component.spec.ts
libs/designsystem/src/lib/components/progress-circle/progress-circle-ring.component.svg
libs/designsystem/src/lib/components/progress-circle/progress-circle-ring.component.ts
libs/designsystem/src/lib/components/progress-circle/progress-circle.component.html
libs/designsystem/src/lib/components/progress-circle/progress-circle.component.spec.ts
libs/designsystem/src/lib/components/progress-circle/progress-circle.component.ts

This PR closes #1468
Issue Number: #1468
Now the progress circle value respects an upper bound for each size (sm: 95, md: 96, lg:97). Values between the upper bound and 99 will show as the upper bound value, so the start and end line cap of the stroke does not merge and show like 100.

Fixed Progress Circle showing full progress on values close to 100

---

tsconfig.base.json

This PR closes N/A.
Removed the checks for unused params and variables, because they were interfering with auto-generated files. 
Once we move to eslint (#1317), we can have this as a linting step `no-unused-vars` instead of a compile time check, so it is less obstructive.  

🔧 Remove no unused locals and no unused params check

---

apps/cookbook/src/app/showcase/card-showcase/card-showcase.component.ts

No issue has been created for this - I went rouge and just submitted a PR 🥷
The cookbook API description for Card used to say `hasPadding` defaults to `true`. This is not the case as it is undefined by default - and hence falsy. 
From `libs/desingsystem/src/lib/components/card/card.component.ts`:
```javascript
export class CardComponent implements OnInit, OnDestroy {
@Input() title: string;
@Input() subtitle: string;
@Input()
hasPadding: boolean;
...
```
When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/au …

Correct card documentation to say hasPadding defaults to false 

---

libs/designsystem/src/lib/components/item/item.component.integration.spec.ts
libs/designsystem/src/lib/components/list/list.component.scss

This PR closes #1678
Padding is now added to the surrounding kirby-list-item wrapper component that was introduced with virtual scrolling in lists #1497.  

Apply spacing to kirby-list-item when hasItemSpacing is true

---

apps/cookbook/src/app/examples/examples.component.ts
apps/cookbook/src/app/examples/form-field-example/form-field-example.component.ts
apps/cookbook/src/app/examples/modal-example/modal-example-configuration/modal-example-configuration.component.ts
apps/cookbook/src/app/examples/modal-example/modal-example-default.component.ts
libs/designsystem/src/lib/components/button/button.component.integration.spec.ts
libs/designsystem/src/lib/components/calendar/calendar.component.initialization.spec.ts
libs/designsystem/src/lib/components/calendar/calendar.component.spec.ts
libs/designsystem/src/lib/components/calendar/helpers/calendar.helper.ts
libs/designsystem/src/lib/components/form-field/form-field.component.spec.ts
libs/designsystem/src/lib/components/form-field/form-field.component.ts
libs/designsystem/src/lib/components/item/item.component.integration.spec.ts
libs/designsystem/src/lib/components/list/directives/infinite-scroll.directive.spec.ts
libs/designsystem/src/lib/components/list/directives/infinite-scroll.directive.ts
libs/designsystem/src/lib/components/list/list.component.spec.ts
libs/designsystem/src/lib/components/modal/alert/alert.component.spec.ts
libs/designsystem/src/lib/components/modal/alert/alert.component.ts
libs/designsystem/src/lib/components/modal/modal-wrapper/compact/modal-compact-wrapper.component.ts
libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.testbuilder.ts
libs/designsystem/src/lib/components/modal/services/alert.helper.spec.ts
libs/designsystem/src/lib/components/modal/services/modal.helper.spec.ts
libs/designsystem/src/lib/components/modal/services/modal.helper.ts
libs/designsystem/src/lib/components/page/page.component.spec.ts
libs/designsystem/src/lib/components/page/page.component.ts
libs/designsystem/src/lib/helpers/platform.service.ts
libs/designsystem/src/lib/kirby.module.ts
libs/designsystem/src/lib/types/window-ref.ts

This fixes the issue of WindowRef injection being broken when using KirbyModule in (jest based) DRB integration tests, which in turn has prevented the integration tests from using non-mocked Kirby components.
This PR closes #1624 
KirbyModule can now be injected and used in jest test without errors caused by to broken WindowRef injection.
**NOTE: No changes to the functionality are introduced. I've run the test spec and I've spun up the cookbook to verify that both still work, and I've also verified that the change fixes the DI problem when using KirbyModule from a DRB test.**
When the pull request has been approved it will be …

WindowRef is now injected through a wrapper class

---

libs/designsystem/src/lib/components/button/button.component.ts

This PR closes #1679 
The `text` input property has simply been removed.

Remove unused 'text' input property from Button Component

---

.github/workflows/build.yml
config/helm/charts/spa/Chart.yaml
config/helm/charts/spa/README.md
config/helm/charts/spa/templates/_helpers.tpl
config/helm/charts/spa/templates/deployment.yaml
config/helm/charts/spa/templates/ingress.yaml
config/helm/charts/spa/templates/service.yaml
config/helm/charts/spa/values.yaml

None - the CI/CD pipeline is down. This is a hot fix. 
Before we acquired helm charts from a remote repository which has now been made private. The files we were dependent on from this repository has been included in the `config/helm` folder as part of the Kirby repository.

Hotfix CI/CD pipeline by adding Helm charts to repository

---

libs/designsystem/src/lib/components/list/list.component.spec.ts
libs/designsystem/src/lib/components/list/list.component.ts

This PR closes #1725 
This PR is a fix to a regression introduced when implementing virtual scroll in #853, more specifically [this line in list.component.ts](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/list/list.component.ts#L200), introduced by 4bf824da3cd7e1f49310fc8465b6f53f0d8368ea. 
Previously, this check had been limited to guard for `this.items` being null, but now it was changed to return if the `items` input had length 0. Naturally, `ngOnChanges` fires when the `items` input is changed, also if it is set to an empty array. 
So in the specific case when the last item is removed and `items` gets length 0, the `_groupedItems` which the UI looks at when rendering the sections and their respective items, never gets updated, and …

Fixed issue where removing last item in list with sections did not update list view to be empty

---

libs/designsystem/src/lib/components/item/item.component.scss

This PR closes #1745 
There is no longer extra space between list items.
In https://github.com/kirbydesign/designsystem/pull/1497 the markup structure for lists were modified which introduced extra space between list items.
**❌ Before**
**✅ After**

Fix wrong spacing between items in kirby-list

---

apps/cookbook/src/app/page/header/header.component.ts

This PR closes #1757 
There is no longer a "Design" link in the cookbook navigation menu.
When we moved to Github Pages https://kirby.design was redirected to https://cookbook.kirby.design.

Remove link to https://kirby.design from cookbook navigation menu

---

libs/designsystem/src/lib/components/item/item.component.scss

This PR closes #1711 
This PR is related to #1752.

Fix visual bug where rounded corners were missing from top corners in first item in list section

---

libs/designsystem/src/lib/scss/_global-styles.scss

This PR closes #1770
Global styles is initialized on the shadow root of my web component when I import them in a WEB Component

Added :host to _global-styles for encapsulation in WEB Components

---

libs/designsystem/src/lib/components/tabs/index.ts
libs/designsystem/src/lib/components/tabs/tabs.service.ts

This PR closes #1789
With TypeScript 4.3 we can't import types from derived dependencies. `IonRouterOutlet` is part of `@ionic/angular` and we get that through Kirby. So when we update to TypeScript 4.3, we need to have `@ionic/angular` as part of our `package.json`, which is not desirable.
This pull requests re-exports `IonRouterOutlet` through Kirby, so we don't need to have `@ionic/angular` as part of the `package.json` in our project.
When the pull request has been approved it will be automatically merged to master via …

Re-export IonRouterOutlet

---

libs/designsystem/testing-base/src/lib/components/mock.button.component.ts
libs/designsystem/testing-base/src/lib/components/mock.calendar.component.ts
libs/designsystem/testing-base/src/lib/components/mock.popover.component.ts

This PR closes _no issue_. 
I went rogue on this one 🥷
The mocks for calendar, popover and button were out of date. 
I've just ran `npm run generate-mocks` to update them and committed the results.
Nope 🙅‍♂️

Update mocks for button, popover and calendar

---

libs/designsystem/testing-base/src/lib/directives/mock.fit-heading.directive.ts
libs/designsystem/testing-base/src/lib/mock-directives.ts

This PR closes #1642
A mock has been created and exposed for the fit heading directive. 
Nope 🙅‍♂️

Add new MockFitHeadingDirective

---

libs/designsystem/src/lib/components/chart/chart.component.spec.ts
libs/designsystem/src/lib/components/chart/chart.component.ts

This PR closes #1880
The ChartComponent now waits for the canvas element to have a non-zero width and height before calling `renderChart`.
The bug stemmed from the canvas having no width or height when afterViewInit is called, when inside an ionic component. For example when slotted in a Kirby-page. 
This caused the chart to be rendered with no width and height but the initial animation still played (albeit not visibly). When the ionic elements then are hydrated and ready to go the canvas element is resized and the chart is visible. But no animation is played as it has already been played once when it had no width or height. 
I've had a hard time testing this and I've added no test as of now. It is not possible to see if animations are in progress. 
Any suggestions for how to test this …

Fix bug causing no animations to be played on first draw of the chart component

---

libs/designsystem/src/lib/components/segmented-control/segment-item.ts
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.spec.ts
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts

This PR closes #1890
It is now possible to specify an icon with a custom name for the Segmented Control badge. 

Make custom icon name usable in Segmented Control badge

---

libs/designsystem/src/lib/components/tabs/tab-button/tab-button.component.scss

This PR closes #1892 
The small badge should be positioned differently from the medium size badge in the Tabs component, and now it is 🎉 

Adjust position for small badge in tabs

---

libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts

This PR closes no issue. It is a quickfix.
Segmented Item badge set to `null` would throw an error. 

Fix error when badge is null in Segmented Control

---

libs/designsystem/src/lib/components/reorder-list/reorder-list.component.ts

Oh crap, do I need to create one?
This fixes a bug, that the "feedback" layer of a Re-order list appears "too late" (and then doesn't disappear) when Component (containing re-order list) is configured with change-detection being `ChangeDetection.OnPush`. 
To test this, replace the contents of: `apps/cookbook/src/app/examples/modal-example/modal-route-example/modal-route-page1-example.component.ts` with the following code:
```typescript
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ReorderEvent } from '@kirbydesign/designsystem';
@Component({
selector: 'cookbook-modal-route-page-1-example',
template: `
<kirby-page-title>Modal Page 1/2</kirby-page-title>
<kirby-reorder-list
(itemReorder)="doReorderItem($event)" …
```

Bugfix: Feedback on re-order list with OnPush-detection

---

libs/designsystem/src/lib/components/calendar/calendar.component.scss

This PR closes #1914
We're unsetting the color on button in order to remove the one provided as default by safari. 

Fix calendar buttons being blue in Safari on iOS 15

---

apps/cookbook/src/app/showcase/fonts-showcase/fonts-showcase.component.html

No issue for this smol fix!
I corrected the documentation for the font size that is applied when using h3/kirby-text-medium class.

Fix wrong docs for font size in medium text

---

libs/designsystem/src/lib/scss/_utils.scss
scripts/publish.js

This PR closes #1936 
Forward Sass module utils instead of copying file from `core` to `designsystem`.

Fix Sass module configuration failure in relationsbanken

---

.github/workflows/publish.yml

🐛 Should not run when PR merged (no changes to libs/)

---

apps/cookbook/src/app/showcase/toast-showcase/toast-showcase.component.ts

This PR closes no issue. 
The `danger` messageType for the toast has been deprecated: #1499 
But the original PR forgot to remove it from the documentation - hence this PR. 

Remove 'danger' messageType from cookbook API description

---

libs/designsystem/src/lib/components/dropdown/dropdown.component.html
libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts

This PR closes #1987 
Click on `<kirby-dropdown>` button will no longer submit form containing the dropdown.

🐛 BUGFIX: Prevent Kirby Dropdown from submitting form

---

libs/designsystem/src/lib/components/button/button.component.scss
libs/designsystem/src/lib/components/modal/action-sheet/action-sheet.component.spec.ts

This PR closes #2018 
The cancel button color of kirby-action-sheet is now being rendered as a white button.

Fixed wrong cancel-button color on action-sheet

---

libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts

This PR closes #2031
No ResizeObserver exceptions thrown in Azure App Insight when navigating to select pages
```
/drb/investment/securities
/drb/investment/overview
/drb/inbox
```
Other routes should be thoroughly tested.
It's unclear if the changes has any sideeffects. It should be tested.

Mute "ResizeObserver loop limit exceeded" exception

---

libs/designsystem/src/lib/components/calendar/calendar.component.initialization.spec.ts
libs/designsystem/src/lib/components/calendar/calendar.component.spec.ts

This PR closes no issue 🥷 
We got an awful lot of `ERROR: 'NG0303: Can't bind to 'noDecoration' since it isn't a known property of 'button'.'` since 2754df7eebdd0cacf5903b5bf74e6a9674cd327c introduced buttons in the calendar. 

Declare button in calendar tests

---

libs/designsystem/testing-base/src/lib/components/mock.card.component.ts
libs/designsystem/testing-base/src/lib/components/mock.modal-footer.component.ts

This PR closes no issue. I've gone rogue 🥷 
Missing input properties has been added to mocks.

Add missing input properties to card & modal footer mocks

---

readme.md

V1 was a looong time ago - we should remove the migration guide notice from the readme. 
It makes it seem outdated 😄

Remove v1 migration guide notice from readme

---

libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts

This PR closes #2031 
See this comment: https://github.com/kirbydesign/designsystem/issues/2031#issuecomment-1070549974

Avoid ResizeObserver loop by delaying scaling of header to next cycle

---

libs/designsystem/src/lib/components/item/item.component.scss

This PR closes #2117
Item will not inherit custom properties like `--padding-top` from 'above', as this poses a problem when an item is used within e.g. a modal, where `ion-content` defines `--padding-top` and `--padding-bottom`. 
Now, it has to be specifically set on the item. This bug was introduced in v. 5.1.1, as mentioned [here](https://github.com/kirbydesign/designsystem/pull/2029/files#diff-47a4f9a6346abfbf0d4e08bccd42083ab3cf87d2871dc195a50fcd143ecf2c0bR10-R11
)
When the pull request has been approved it will be automatically merged to `stable` via …

Set fallback value for --padding-top/bottom on item

---

apps/cookbook/src/app/examples/examples.module.ts

This PR closes no issue
Something has gone wrong when rebasing causing the CardExampleModule to not be imported in `examples.module.ts`. I've added it back in. 

Reintroduce accidentally removed module import

---

libs/designsystem/src/lib/components/form-field/input/input.component.scss

Interaction state hover for input

---

libs/designsystem/src/lib/components/accordion/accordion-item.component.html
libs/designsystem/src/lib/components/accordion/accordion-item.component.scss

This PR closes #2089
Hover background styles are applied when hovering the whole item, also when expanded. 
The cursor is only a pointer when hovering over the header, as it is only the header that is interactive. 

Interaction state hover for accordion

---

libs/designsystem/src/lib/components/toggle/toggle.component.scss

This PR closes #2088
The box shadow on the toggles handle now matches the original design.  

Adjust toggle handle box shadow

---

libs/designsystem/src/lib/components/avatar/avatar.component.ts
libs/designsystem/src/lib/components/button/button.component.ts
libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts
libs/designsystem/src/lib/components/dropdown/dropdown.component.ts
libs/designsystem/src/lib/components/form-field/input/input.component.ts
libs/designsystem/src/lib/components/icon/icon.component.ts
libs/designsystem/src/lib/components/item/item.component.ts
libs/designsystem/src/lib/components/popover/popover.component.ts
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts
libs/designsystem/testing-base/src/lib/components/mock.avatar.component.ts
libs/designsystem/testing-base/src/lib/components/mock.button.component.ts
libs/designsystem/testing-base/src/lib/components/mock.dropdown.component.ts
libs/designsystem/testing-base/src/lib/components/mock.icon.component.ts
libs/designsystem/testing-base/src/lib/components/mock.input.component.ts
libs/designsystem/testing-base/src/lib/components/mock.item.component.ts
libs/designsystem/testing-base/src/lib/components/mock.popover.component.ts
libs/designsystem/testing-base/src/lib/components/mock.segmented-control.component.ts

See https://github.com/kirbydesign/designsystem/pull/2093#pullrequestreview-905746288 for context.

Allow input properties with enum type to be provided as string

---

apps/cookbook/src/app/examples/examples.common.ts
libs/designsystem/src/lib/components/icon/icon-registry.service.spec.ts
libs/designsystem/src/lib/components/icon/icon-registry.service.ts
libs/designsystem/src/lib/components/icon/icon-settings.ts
libs/designsystem/src/lib/components/icon/index.ts

This PR closes #2062
The constructor for the IconRegistryService no longer accounts for any injected IconSettings. 
Icons can no longer be injected in a module like this: 
```
providers: [
{ 
provide: ICON_SETTINGS, 
useValue: iconSettings 
}
]
```
Instead, the IconRegistryService should be used, as [per the documentation](https://cookbook.kirby.design/#/home/showcase/icon): 
```
export class @NGModule {
constructor(iconRegistryService: IconRegistryService) {
iconRegistryService.addIcons(this.icons);
}
}
```

Remove option to inject IconSettings via IconRegistryService constructor

---

apps/cookbook/src/app/examples/chart-deprecated-example/examples/chart-deprecated-example-bar.component.ts
apps/cookbook/src/app/examples/chart-deprecated-example/examples/chart-deprecated-example-column.component.ts
apps/cookbook/src/app/examples/slide-button-example/slide-button-example.component.ts
libs/designsystem/src/lib/components/modal/alert/alert.component.html
libs/designsystem/src/lib/components/modal/alert/alert.component.spec.ts
libs/designsystem/src/lib/components/modal/alert/alert.component.ts
libs/designsystem/src/lib/components/modal/alert/config/alert-config.ts
libs/designsystem/src/lib/components/modal/services/alert.helper.ts

This PR closes #2063 
`okBtnText` and `cancelBtnText` properties of the AlertConfig interface has been removed. The AlertConfig interface is used by consumers to configure the `ModalController` with the alert flavor. 
Additionally, the input-props of the AlertComponent has been changed to reflect this. This makes it a breaking change to the alert component too, but this should have low to no impact on consumers, as the alert component should not be used on its own, but rather through the ModalController/AlertHelper configuration. 
`okBtnText` and `cancelBtnText` of `AlertConfig` are removed, and the existing `okBtn` and `cancelBtn` should be used instead, as a direct replacement for these. 
If for some reason the AlertComponent is used directly in markup as `kirby-alert` instead of …

Remove deprecated okBtnText and cancelBtnText from AlertConfig

---

libs/designsystem/src/lib/components/modal/modal-wrapper/config/modal-config.ts
libs/designsystem/src/lib/components/modal/services/modal.controller.ts

This PR closes #2064
Dim is removed 🥳 
Dim is no longer a configurable option, so it should be removed from ModalConfig.

Remove deprecated dim property on ModalConfig

---

libs/designsystem/src/lib/components/chart/chart.component.spec.ts
libs/designsystem/src/lib/components/chart/chart.component.ts
libs/designsystem/testing-base/src/lib/components/mock.chart.component.ts

This PR closes #2068
The dataLabels property has been fully removed.

Remove deprecated 'dataLabels' property

---

libs/core/src/scss/base/_typography.scss
libs/core/src/scss/base/_variables.scss
libs/core/src/scss/themes/_colors.scss
libs/designsystem/src/lib/components/flag/flag.component.scss
libs/designsystem/src/lib/components/flag/flag.component.spec.ts

This PR closes #2041 
We introduce a new color design token and use it for `danger` theme on Flag components. Other components' danger color is not affected.
We also introduce a new font weight `medium` with a CSS font-weight value of 500. This new font weight is used for text in Flag components.

Flag: New danger color and heavier font weight

---

apps/cookbook/src/app/examples/alert-example/alert-example.component.ts
apps/cookbook/src/app/examples/list-swipe-example/list-swipe-example.component.ts
libs/designsystem/src/lib/components/toast/config/toast-config.ts
libs/designsystem/src/lib/components/toast/services/toast.helper.spec.ts
libs/designsystem/src/lib/components/toast/services/toast.helper.ts

This PR closes #1979
So long danger toast 
More details in #1085 and #1979

Remove deprecated toast danger MessageType

---

libs/designsystem/src/lib/components/card/card-header/card-header.component.scss
libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.scss
libs/designsystem/src/lib/components/radio/radio.component.scss
libs/designsystem/src/lib/components/tabs/tabs.component.scss
libs/designsystem/src/lib/components/tabs/tabs.component.spec.ts

This PR closes no issue. 
The issue described in #2158 is also present for other CSS custom properties, so I have added px back everywhere #2146 removed it for CSS Custom Properties. 

Add back CSS Custom Property px unit

---

libs/designsystem/src/lib/components/list/index.ts
libs/designsystem/src/lib/components/list/list.directive.ts
libs/designsystem/src/lib/components/list/list.module.ts
readme.md

This PR closes #2066 
There are now no more deprecated list directives.

Remove deprecated list directives

---

libs/designsystem/src/lib/components/segmented-control/segment-item.ts
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts

This PR closes #2065
It is no longer an option to mark a `SegmentItem` in the `items` input of `SegmentedControl` as checked.
Use `selectedIndex` or `value` on `<kirby-segmented-control>` instead of setting `checked` on any of the `SegmentItem`s.

Remove deprecated 'checked' property on SegmentItem interface

---

libs/core/src/scss/interaction-state/_hover.scss
libs/core/src/scss/interaction-state/_interaction-state.utilities.scss
libs/core/src/scss/interaction-state/_layer.scss
libs/core/src/scss/interaction-state/ionic/_hover.scss
libs/designsystem/src/lib/components/button/button.component.scss
libs/designsystem/src/lib/components/calendar/calendar.component.scss
libs/designsystem/src/lib/components/checkbox/checkbox.component.scss
libs/designsystem/src/lib/components/chip/chip.component.scss

This PR closes #2136 
`$flip` is now `$make-lighter` in `apply-state()`. 

Change state layer 'flip' argument to 'make-lighter'

---

angular.json
libs/core/src/scss/interaction-state/_active.scss
libs/core/src/scss/interaction-state/_index.scss
libs/core/src/scss/interaction-state/_interaction-state.utilities.scss
libs/designsystem/src/lib/components/accordion/accordion-item.component.scss
libs/designsystem/src/lib/components/button/button.component.scss
libs/designsystem/src/lib/components/calendar/calendar.component.scss
libs/designsystem/src/lib/components/card/card.component.scss
libs/designsystem/src/lib/components/chip/chip.component.scss

This PR closes #2149 
Everywhere we use the hover interaction state layer we now also use active/pressed interaction state layer.

Apply apply-active mixin to various components

---

libs/designsystem/src/lib/components/popover/popover.component.ts

This PR closes #2180 
The hide functionality has been refactored a bit to ensure that the element is in fact showing, before doing hide logic.
Furthermore, the backdropClick listener was removed, because it was not functional, as described in the commit message: 
> The event listener was not called because dropdowns onBlur event was
> always fired first, closing the dropdown including the popover
> component. In fact it was only called when clicking inside the dropdown
> because onBlur is not fired then - and thus it is useless at this point.
> 
> Components using popover (dropdown only right now) should take care of
> calling hide() at the appropriate time themselves, e.g. in onBlur.
The following tasks should be carried out in sequence in order to follow [the process of …

Fix popovers hide() being called twice

---

libs/designsystem/src/lib/components/popover/popover.component.ts

This PR closes #2204 
We make sure to check that we are not actually scrolling inside the popover, before we prevent the touchmove event. 

Only prevent touchevent outside popover

---

apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.ts
libs/core/src/scss/interaction-state/ionic/_active.scss
libs/core/src/scss/interaction-state/ionic/_index.scss
libs/designsystem/src/lib/components/checkbox/checkbox.component.scss
libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.scss
libs/designsystem/src/lib/components/form-field/input/input.component.scss
libs/designsystem/src/lib/components/item/item.component.scss
libs/designsystem/src/lib/components/page/page.component.scss
libs/designsystem/src/lib/components/radio/radio.component.scss
libs/designsystem/src/lib/components/range/range.component.scss
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.scss
libs/designsystem/src/lib/components/slide-button/slide-button.component.scss
libs/designsystem/src/lib/components/toggle/toggle.component.scss

This PR closes #2197 fixes #2198
An ionic-specific mixin has been created for those of ionics components that use the  `--background-activated` and `--background-activated-opacity` approach. 
Unfortunately that is not the case for all Ionics components so custom approaches has been implemented for those and some of our non-ionic based components.
Active state should not be overwritten for selectable items, it should follow the same conventions as any other component. If item has `selectable="true"` we want to make sure it has the appropriate active state. 
For most, migration should be fairly simple - just remove `--kirby-item-background-activated`-related CSS.
The following tasks should be carried out in sequence in order to follow [the process of …

Active state for ionic components and special cases

---

angular.json
package.json

This PR closes #2203
Also i got a bit carried away and submitted #2209 which removes the e2e app. There's no reason for having it. 
A "production builds by default" initiative (see: https://github.com/angular/angular-cli/commit/656f8d75a3368a5affd1c55145841123dafdb007) has resulted in our development configurations being the production settings. 
I've added a 'development' configuration which can be used when developing locally; it uses the old defaults which are better for development.
Also i've tried to tidying it up a little.

Fix slow hot reloading

---

libs/core/src/scss/base/_variables.scss
libs/core/src/scss/interaction-state/_interaction-state.utilities.scss
libs/designsystem/src/lib/components/accordion/accordion-item.component.scss
libs/designsystem/src/lib/components/button/button.component.scss
libs/designsystem/src/lib/components/calendar/calendar.component.scss
libs/designsystem/src/lib/components/card/card.component.scss
libs/designsystem/src/lib/components/chip/chip.component.scss
libs/designsystem/src/lib/components/item/item.component.scss
libs/designsystem/src/lib/components/page/page.component.scss

This PR closes #2211 
Before the loudness scale was non-linear: Mostly in 4% increments but with some arbitrary variations (8% increments).
During UX review we realised that we need more levels in the scale.
This PR adds more levels and shifts the scale so it goes from (small to large) `xxxs` to `xxxxl` instead of `s` to `xxxxxxxl` 😎

Refactor loudness scale

---

libs/core/src/scss/base/_functions.scss

This PR closes #2162 
Reintroduces Sass strip-unit utility function

Reintroduce sass strip-unit utility function

---

libs/designsystem/src/lib/components/accordion/accordion-item.component.html
libs/designsystem/src/lib/components/accordion/accordion-item.component.scss

This PR closes #2226 
Hover and active will only be effective when you interact with the header of each Accordion item.
<table>
<tr>
<th>Current (prod)</th>
<th>Interaction states before this PR</th>
<th>Interaction states after this PR</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/150451/167113707-ceca8880-1b5a-41b6-857e-a4f9b738deaa.mov
</td>
<td>
https://user-images.githubusercontent.com/150451/167113555-68b173af-c82e-4690-9ad0-7c2d43394411.mov
</td>
<td>
https://user-images.githubusercontent.com/150451/167113612-b478a3fe-8eff-4629-ab83-945fe964e401.mov
</td>
</tr>
</table>
The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of- …

Adjust hover and active area on Accordion

---

libs/designsystem/src/lib/components/button/button.component.scss

This PR closes #2252
After introducing the content layer, some of the old styling added padding within the small button, while the content layer itself also defined some padding.
We now use the custom properties defined on the content layer to control padding throughout. 

Wrong padding in small button

---

libs/designsystem/src/lib/components/button/button.component.scss

This PR closes #2083 
Shadow added when dropdown is white!

Add elevation to dropdown with attention level 2

---

libs/designsystem/src/lib/components/item/item.component.html
libs/designsystem/src/lib/components/item/item.component.ts
libs/designsystem/src/lib/components/list/list.component.ts

This PR closes #2241
Because kirby-item is projected into the list we currently query all the items in the list and manually set their selectable state, because we can't bind to the input of item in the list template.
This means that we need to manually trigger change detection when we have changed the state of the item component, for it to sync with the view correctly, and become clickable.
When the pull request has been approved it will be automatically merged to `stable` via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/aut …

Run manual CD when changing items in list

---

apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.ts
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts

This PR closes #2235 
Introduced a new input attribute to the segmented-control component (disableChangeOnSwipe), which sets the scrollable attribute on the ion-segment

segmented-control - disable change on swipe attribute

---

.github/CODEOWNERS
apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.ts
libs/core/src/scss/base/_functions.scss
libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts
libs/designsystem/src/lib/components/dropdown/dropdown.component.scss
libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts
libs/designsystem/src/lib/components/item-sliding/item-sliding.component.spec.ts
libs/designsystem/src/lib/components/modal/services/action-sheet.helper.spec.ts
libs/designsystem/src/lib/components/popover/popover.component.ts
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts
package-lock.json
package.json

**dropdown** - experimental popover feature: Fix popovers hide() being called twice (#2195)
**dropdown** - experimental popover feature: Only prevent touchevent outside popover (#2205)
**segmented-control** - add new option to disable change on swipe (#2237)

Release version 5.4

---

libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.scss

This PR closes #2265 closes #1744
Segmented Control now gets the correct state for hover and active when interacting with an already selected segment. 
This includes a small refactor to get rid of the wrapper element around each segment-button in the Segmented Control template, as this was the culprit for not being able to interact with the underlying segment. This `div` wrapper element with `position: relative` was originally introduced to be able to place a badge via `top/left/right` css properties, but is now removed in favor of an `ng-container` that will not clutter the DOM. 
The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) …

Enable click on selected item in Segmented Control

---

libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.html
libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.ts

This PR closes no issue. Just a quick houskeeping task found while looking at #2258 
The implemented logic no longer works, it is still the original ionicon that is used. 
Therefore, the `close-outline` icon is now used instead, which is possible because the `close-outline` and our own `close` icon are visually identical.  

Remove fab sheet icon substitution logic

---

libs/designsystem/src/lib/components/button/button.component.scss

This PR closes #2245 
On small buttons with icon only, the icon inside is reduced from 24px to 16px since it did apper too large for the button size.

Change size of icon on icon-only buttons

---

libs/designsystem/src/lib/components/chart-deprecated/chart-deprecated-helper.ts

This fixes error "require is not defined" by using import instead of require.

Use import instead of require for highcharts

---

libs/core/src/scss/base/_functions.scss
libs/core/src/scss/base/_variables.scss
libs/designsystem/src/lib/components/button/button.component.integration.spec.ts
libs/designsystem/src/lib/components/button/button.component.scss
libs/designsystem/src/lib/components/page/page.component.html
libs/designsystem/src/lib/components/page/page.component.scss
libs/designsystem/src/lib/components/page/page.component.spec.ts
libs/designsystem/src/lib/components/page/page.component.ts

This PR closes #2219
- The toolbar height is set depending on the size of the screen set as follows*:
- \>= medium: 'xxxxl'/64px
- < medium: 'xxxl'/56px (default)
- 'xxl'/48px (if the phone is an iPhone with a notch)
The presence of a notch on the iPhone is not easily detectable but it has been agreed that a defined ios-safe-area-top above 32px will be interpreted as an iPhone with a notch
- A 1px 'semi-light' bottom border is added to the toolbar when content is scrolled - implements #2040.
- The distance between the toolbar and the page content has been Increased.
- The toolbar button styling applies to icon-only buttons on kirby-page avoiding kirby-modal.
- The toolbar styling now works with all kinds of kirby-action templates - not necessarily using the kirby-page-action element.
The …

Add dynamic toolbar height and refine layout

---

libs/designsystem/src/lib/kirby.module.ts

Fix "Identifier 'exports' has already been declared"

---

libs/designsystem/src/lib/components/form-field/_form-field-inputs.shared.scss
libs/designsystem/src/lib/components/form-field/directives/date/date-input.directive.spec.ts
libs/designsystem/src/lib/components/form-field/input/input.component.integration.spec.ts
libs/designsystem/src/lib/components/form-field/input/input.component.scss
libs/designsystem/src/lib/components/form-field/input/input.component.spec.ts

This PR closes #2301 
Fixes visual bug: Mask/placeholder and input text has wrong position (size `md`)
At unchanged base font size there should be no visual changes. Otherwise improvement by scaling sizes properly relative to base font size.
But UX review should try to verify that there are no visual regressions introduced.
**Before**
**After**

Short term fix for input field styles

---

libs/designsystem/testing-base/src/lib/components/mock.segmented-control.component.ts

This PR closes no issue. 
The `disableChangeOnSwipe` input property has been added to the `MockSegmentedControlComponent`. 

Add 'disableChangeOnSwipe' input property to 'MockSegmentedControlComponent'

---

libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.integration.spec.ts
libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts
libs/designsystem/src/lib/components/dropdown/dropdown.component.html
libs/designsystem/src/lib/components/dropdown/dropdown.component.ts

This PR closes #2317
Fix selection problem on dropdown with popover in Safari/WebView.

Fix item-selection on dropdown with popover in safari

---

apps/cookbook/src/app/page/header/header.component.ts
package-lock.json
package.json

Minor version was not correctly updated prior to releasing v6.1.
In addition, this adds a fix for a faulty changelog link.

Update minor version

---

libs/designsystem/src/lib/components/dropdown/dropdown.component.ts

This PR closes #2153
The issue was caused by the event listener being set up once using the renderer on afterContentChecked. If the slotted items changed, an if sentence caused the new items to not have their click listener set up. Now we do it everytime the kirbyItemsSlotted attribute is updated. We also make sure to unlisten old items when it changes & onDestroy.

Fix slotted items being unclickable after update

---

apps/cookbook/src/app/showcase/fab-sheet-showcase/fab-sheet-showcase.component.html
libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.html

This PR closes #2402
The housekeeping done in #2302 only worked in the cookbook because we have ionicons installed which meant that the ion-fab-button could correctly locate the close icon. Projects should not have to install Ionicons, so this PR introduces a workaround where we place our own close icon where ion-fab-button expects it to be. 
Therefore, the custom close icon introduced in #2302 is removed again, and a description of how to place the existing close icon as needed is added instead.
This is already how it is done in the DRB project, so it solves the problem described in #2402. With this fix installed, we now get the following close icon: 
https://user-images.githubusercontent.com/42470636/182592949-05ef9470-4b43-467b-9a75-ba87116d757f.mov
The following tasks should be …

Missing close icon in FAB-sheet 

---

libs/designsystem/src/lib/components/dropdown/dropdown.component.ts

This PR closes #2335 
Prevent page refresh when dropdown is scrolled on touch devices

Fix dropdown scroll problem on touch devices

---

libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts

closes #2388 closes #2349
I have refactored the wrapper click prevention to instead determine if the click is coming from the `ion-segment-button` or its contents. This should exclude both the wrapper, and also other elements like the badge. 

Avoid removing focus from Segmented Control on embedded badge click

---

libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.ts

This PR closes #2398
Fab sets backdrop on mobile devices.

Fix missing fab-sheet backdrop on mobile devices

---

libs/designsystem/src/lib/components/modal/action-sheet/action-sheet.component.scss

Closes https://github.com/kirbydesign/designsystem/issues/2340
When the cancel button receives focus by "tabbing with keyboard" a blue focus ring appears.

Apply focus styles to Action Sheet cancel button

---

libs/designsystem/src/lib/testing/test-helper.ts

Adding a short timeout when waiting for ResizeObserver in modal helper
test seems to fix failing tests
This PR closes NO ISSUE

✅ Add 1ms timeout

---

libs/designsystem/src/lib/components/tabs/tab-button/tab-button.component.scss

This PR closes #2244 
This solution is temporary. Tabs on desktop will eventually be obsolete and replaced by the new navigation menu.

Add missing hover and active states to tabs on desktop

---

libs/core/src/scss/interaction-state/_focus.scss
libs/designsystem/src/lib/components/accordion/accordion-item.component.html
libs/designsystem/src/lib/components/accordion/accordion-item.component.scss
libs/designsystem/src/lib/components/accordion/accordion-item.component.ts
libs/designsystem/src/lib/components/modal/action-sheet/action-sheet.component.scss
libs/designsystem/src/lib/components/tabs/tab-button/tab-button.component.scss

This PR closes #2236 
Applies alternative focus style. Instead of displaying focus ring the background color is changed by adjusting the state layer opacity.
Dropdown will be solved by https://github.com/kirbydesign/designsystem/issues/2342

Change background color on focus

---

libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.html
libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.ts

This PR closes #2452
The backdrop should now be in sync with the action sheet, so it shows whenever the action sheet is opened. 

Fix backdrop showing up when fab is closed

---

apps/cookbook/src/app/examples/card-example/examples/card-background-image-example/card-background-image-example.component.html
apps/cookbook/src/app/examples/card-example/examples/card-css-background-image-example/card-css-background-image-example.component.html
apps/cookbook/src/app/examples/card-example/examples/card-themecolor-example/card-themecolor-example.component.html
apps/cookbook/src/app/examples/card-example/examples/card-themecolor-example/card-themecolor-example.component.ts
apps/cookbook/src/app/showcase/card-showcase/card-showcase.component.ts
libs/designsystem/src/lib/components/card/card.component.scss
libs/designsystem/src/lib/components/card/card.component.ts

This PR closes #2443 
This enhancement lets users specify if card has a dark background color. If true the interaction states :hover and :active will be lighter and louder instead of the default "make it darker" and and more subtle "less loud".
Disclaimer: This is almost a one-off thing and the implementation does not allow for any flexibility. It's either or. Users also has to apply the property themselves - it does not apply automagically. 

Use alternative hover and active on dark Cards

---

libs/designsystem/src/lib/components/toggle/toggle.component.scss

This PR closes #2441 
Fixed the gap between ion-toggle and kirby-toggle, that occurred since the ion-toggle behaved as an inline element. The new behavior is making kirby-toggle display inline-flex, which eliminates the gap without changing the outwards behaviour of kirby toggle. 

Fixed bug: toggles inside Kirby item placed too high

---

libs/designsystem/src/lib/components/page/page.component.spec.ts
libs/designsystem/src/lib/components/page/page.component.ts

This PR closes #2521 
kirby-page correctly removes event listeners from window.

Fix memory leak in kirby-page

---

libs/designsystem/src/lib/components/page/page.component.scss

This PR closes #2033 
Now using kirby black for page-title and toolbar instead of black

Using kirby black on ion-tool bar and ion-content instead of using black

---

apps/cookbook/src/app/examples/empty-state-example/empty-state-example.component.html
apps/cookbook/src/app/showcase/empty-state-showcase/empty-state-showcase.component.ts

This PR closes #2508
The Empty State cookbook page now includes documentation and example of custom icon usage.

Update EmptyState cookbook example to include custom icon documentation

---

CHANGELOG.md
libs/core/package.json
libs/designsystem/package.json
package-lock.json
package.json

- **data table** - introduce new Kirby Data Table component ([#2517](https://github.com/kirbydesign/designsystem/pull/2517))
- **dropdown** - enable keyboard navigation in the dropdown ([#2424](https://github.com/kirbydesign/designsystem/pull/2424))
- **formfield** - introduce affix functionality (pre- and suffix) ([#2545](https://github.com/kirbydesign/designsystem/pull/2545))
- **icon** - add update icon ([#2558](https://github.com/kirbydesign/designsystem/pull/2558))
- **local navigation** - introduce **experimental** local navigation component ([#2501](https://github.com/kirbydesign/designsystem/pull/2501))
- **modal** - Add option to show an alert before dismissing modal ([#2514](https://github.com/kirbydesign/designsystem/pull/2514))
- **tabs** - change position of …

Release v7.2.1
